{
 "title": "Distributed Tracing - Tempo",
 "description": "Shows high level API request successes, failures, and trace details.",
 "tags": [
  "tracing",
  "tempo"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "filters": [
      { "id": "2981aa81", "operator": "=", "scope": "span" }
     ],
     "limit": 1000,
     "query": "{name=\"GET /api/v1/test/trace\" || name=~\"GET /api/.*\" || name=~\"POST /api/.*\"}",
     "spss": 10,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Failed Requests (Non-2xx Status)",
   "type": "table",
   "gridPos": { "h": 10, "w": 17, "x": 6, "y": 0 },
   "targets": [
    { "limit": 20, "query": "{status.code=2}", "spss": 10, "tableType": "traces" }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "limit": 1000, "query": "{status=error}", "tableType": "traces" }
   ]
  },
  { "title": "Request Analysis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "filters": [
      { "id": "0b3c1488", "operator": "=", "scope": "span" }
     ],
     "limit": 1000,
     "tableType": "traces"
    }
   ]
  },
  {
   "title": "Recent Traces",
   "type": "table",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 11 },
   "targets": [
    { "limit": 20, "query": "{}", "tableType": "traces" }
   ]
  },
  {
   "title": "Request Execution Errors",
   "type": "timeseries",
   "description": "These occur when a runtime error is invoked",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "filters": [
      {
       "id": "status",
       "operator": "=",
       "scope": "intrinsic",
       "tag": "status",
       "value": "error",
       "valueType": "keyword"
      }
     ],
     "limit": 20,
     "tableType": "traces"
    }
   ]
  },
  { "title": "Trace Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Trace Explorer",
   "type": "traces",
   "description": "Use this panel to explore specific traces by ID",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  }
 ]
}